name: naviga
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  camera: ^0.10.5+5
  connectivity_plus: ^5.0.2
  dialog_flowtter: ^0.2.0-nullsafety.0
  flutter:
    sdk: flutter
  flutter_tflite: ^1.0.1
  flutter_tts: ^3.8.5
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  get: ^4.6.5
  http: ^1.1.0
  image: ^3.3.0
  intl: ^0.18.1
  logger: ^2.0.2+1
  lottie: ^2.6.0
  permission_handler: ^11.0.1
  speech_to_text: ^6.4.1
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


  assets:
   - assets/
   - assets/ssd_mobilenet.tflite
   - assets/ssd_mobilenet.txt
   - assets/dialog_flow_auth.json
 
    

    